apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask
spec:
  selector:
    matchLabels:
      app: app-flask
  replicas: 2
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: app-flask
        image: docker-tutorial_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000