apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql
  namespace: k8s-database
spec:
  selector:
    matchLabels:
      app: mysql 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env: 

        #use secret instance in real case
        - name: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql 
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
          
 #sudo kubectl create -f mysql-deployment.yaml 
# output deployment.apps/mysql created
  
          
