apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: k8s-database
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    
# to deploy the service : sudo kubectl apply -f mysql-service.yaml 
# output : service/mysql created    
